### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by pedrombasso** [pedrombasso/projet-commande-et-reseaux#1]
- Criar um servidor na Main pra receber os dados do Comunicador.

- Utils.h foi pra raiz por causa dos espacos dos diretorios.

**Comment by edulorandi** [comment]
- [x] Controller-> Communicator, ver como subir o servidor do Comunicator em outro IP.
Sem necessidade ja que os servidores 


    - [ ] Criar um cliente no ServerComunicator pra se comunicar com a Main e enviar os parametros float/double

    - [ ]  Criar um servidor na Main pra receber os dados do ServerComunicador.

    - [ ] Ver como trabalhar com cliente e servidor ao mesmo tempo no Comunicator

**Comment by pedrombasso** [comment]
resaux
delay tem que ser fixo pra todo um boucle


autom:

mandar K e uma velocidade, VREP devolve a posicao 


-- diferenca de posicao do VREP
