### ISSUE TITLE
TODO 21/02

### ISSUE THREAD

**Issue by edulorandi** [pedrombasso/projet-commande-et-reseaux#2]
- Ler o enunciado e entender melhor a parte de redes (tempo de delay, tempo de resposta )

**Comment by edulorandi** [comment]
- [ ] Add a fixed delay "Tr" (check which value is propper) and then make it a random value (also check the range)

This delay will for sure be in the communicator

**Comment by edulorandi** [comment]
- [ ] Make the Controller only send ONE message ( with the sensors array ), and move the robot to this given position (make use of all the network). No receive for now.

Its working, but there's trash comming trought the initial conditions. See non-block connection issue.

**Comment by pedrombasso** [comment]
- [ ] Calculate the time of sending messagens to controller from VREP (two way) throught the network.

- [ ] Add delay to the sending message
